name: jdownloader2
icon: snap/gui/JDownloader.png
version: git
summary: JDownloader
description: JDownloader is a free, open-source download management tool with a huge community of developers that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day!
grade: stable
confinement: strict
base: core20
compression: lzo
architectures:
  - build-on: amd64
    run-on:
      - amd64
parts:
  jdownloader:
    plugin: dump
    source: bin
    organize:
      wrapper: usr/local/bin/jdownloader
      JDownloader.jar: usr/local/bin/
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - default-jre
    stage-packages:
      - default-jre
apps:
  jdownloader:
    command: usr/local/bin/jdownloader
    plugs:
      - home
      - removable-media
      - mount-observe
      - network
      - shutdown
      - desktop
      - desktop-legacy
      - wayland
      - unity7
    extensions:
      - gnome-3-38
